import { CONFIG } from "../config/config.js";
import { normalizeSavedBaseUrl } from "../utils/storage.js";
import { getToken, getSessionId, readJsonStorage } from "../utils/storage.js";

export const state = {
  baseUrl: normalizeSavedBaseUrl(localStorage.getItem(CONFIG.storageKeys.baseUrl) || ""),
  accessToken: getToken(),
  user: readJsonStorage(CONFIG.storageKeys.user, null),
  role: localStorage.getItem(CONFIG.storageKeys.role) || "",
  authMode: "login",
  authLoading: false,
  profileEditing: false,
  lastApiError: "",
  products: [],
  todayDeals: [],
  categories: [],
  cart: [],
  cartItems: [],
  cartLoading: false,
  cartError: "",
  cartCount: 0,
  cartTotal: 0,
  cartUpdatingIds: new Set(),
  cartSelectedIds: new Set(),
  cartKnownItemIds: new Set(),
  addingProductIds: new Set(),
  receivers: [],
  addresses: [],
  selectedReceiverId: null,
  selectedAddressId: null,
  checkoutLoading: false,
  orderSubmitting: false,
  checkoutError: "",
  orderSuccess: null,
  orders: [],
  ordersLoading: false,
  ordersError: "",
  selectedOrder: null,
  selectedOrderHistory: [],
  orderDetailLoading: false,
  orderDetailError: "",
  orderHistoryWarning: "",
  favoriteProducts: [],
  favoriteIds: new Set(),
  favoritesLoading: false,
  favoritesError: "",
  favoritesCount: 0,
  productReviewsByProductId: {},
  productReviewsLoading: {},
  productReviewsError: {},
  myReviews: [],
  myReviewsLoading: false,
  myReviewsError: "",
  reviewSubmitting: false,
  reviewDraft: null,
  reviewRating: 5,
  notifications: [],
  notificationsLoading: false,
  notificationsError: "",
  unreadCount: 0,
  unreadCountLoading: false,
  notificationUpdatingIds: new Set(),
  currentRoute: "home",
  detailLoading: false,
  detailError: "",
  recommendedProducts: [],
  recommendedSimilar: [],
  recommendedOthers: [],
  recommendationsLoading: false,
  recommendationsError: "",
  selectedCategory: "ALL",
  selectedDetailProduct: null,
  selectedVariantId: null,
  selectedQuantity: 1,
  searchTimer: null,
  isLoading: false,
  demoCategories: false,
  demoProducts: false,
  demoDeals: false,
  homeLoadedFromApi: false,
  feedLoading: false,
  feedPage: 0,
  currentSearchQuery: "",
  currentGridScreen: "home",
  impressionsSent: new Set(),
  impressionObserver: null,
  sessionId: getSessionId(),
  banners: [],
  announcements: [],
  recentlyViewed: [],
  uploadingReviewImages: false,
  sourceProducts: [],
  filterFacets: { brands: [], colors: [], sizes: [], maxPrice: 5000000 },
  filters: null,
  compareIds: [],
  compareProducts: [],
  savedForLater: [],
  cartCoupon: "",
  cartCouponDiscount: 0,
  checkoutStep: 1,
  reviewSort: "newest",
  reviewFilterRating: 0,
  reviewSearchQuery: "",
  reviewHelpfulIds: new Set(),
  pdpGalleryIndex: 0,
  pdpActiveTab: "description",
  selectedBrand: null,
  flashSaleEnd: null,
};
