import { createStore } from "./createStore.js";

export const productStore = createStore({
  products: [],
  todayDeals: [],
  categories: [],
  categoryEntities: [],
  banners: [],
  announcements: [],
  recommendedProducts: [],
  recommendedSimilar: [],
  recommendedOthers: [],
  recommendationsLoading: false,
  recommendationsError: "",
  selectedCategory: "ALL",
  selectedDetailProduct: null,
  selectedVariantId: null,
  selectedBrand: null,
  sourceProducts: [],
  filterFacets: { brands: [], colors: [], sizes: [], maxPrice: 5000000 },
  filters: null,
  recentlyViewed: [],
  productReviewsByProductId: {},
  productReviewsLoading: {},
  productReviewsError: {},
  myReviews: [],
  myReviewsLoading: false,
  myReviewsError: "",
  reviewSubmitting: false,
  reviewDraft: null,
  reviewRating: 5,
  reviewSort: "newest",
  reviewFilterRating: 0,
  reviewSearchQuery: "",
  reviewHelpfulIds: new Set(),
  uploadingReviewImages: false,
  detailLoading: false,
  detailError: "",
  pdpGalleryIndex: 0,
  pdpActiveTab: "description",
  selectedQuantity: 1,
  homeLoadedFromApi: false,
  demoCategories: false,
  demoProducts: false,
  demoDeals: false,
  homeApiSections: null,
  compareIds: [],
  compareProducts: [],
  feedLoading: false,
  feedPage: 0,
});
